[package]
name = "minting_dip721"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
candid = "0.8.4"
clap = { version = "4.2.1", features = ["derive"] }
dialoguer = "0.10.4"
ic-agent = "0.23.2"
mime_guess = "2.0.4"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
sha2 = "0.10.6"
thiserror = "1.0.40"
tokio = { version = "1.27.0", features = ["full"] }
